parameters:
    ezpublish.cache_pool.factory.class: eZ\Bundle\EzPublishCoreBundle\ApiLoader\CacheFactory
    ezpublish.http_cache.event_dispatcher.class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher

services:
    # Parameter %ezpublish.cache_pool.class% and cache decorator service are defined
    # in Core configuration, see eZ/Publish/Core/settings/storage_engines/cache.yml for details
    ezpublish.cache_pool:
        class: "%ezpublish.cache_pool.class%"
        factory: ["@ezpublish.cache_pool.factory", getCachePool]
        arguments: ["@ezpublish.config.resolver"]

    ezpublish.cache_pool.factory:
        class: "%ezpublish.cache_pool.factory.class%"
        calls:
            - [setContainer, ["@service_container"]]

    # @todo Needed now?
    ezpublish.http_cache.event_dispatcher:
        class: "%ezpublish.http_cache.event_dispatcher.class%"
        arguments: ["@service_container"]

    # @todo Needed now?
    ezpublish.cache_warmer.config_resolver_cleanup:
        class: eZ\Bundle\EzPublishCoreBundle\Cache\Warmer\ConfigResolverCleanup
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.cache_warmer }
